# Generated by Django 4.0.4 on 2022-05-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='event_admin',
            field=models.BooleanField(default=False),
        ),
    ]
