# Generated by Django 3.1.4 on 2022-05-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220524_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
