# Generated by Django 3.1.4 on 2022-06-09 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20220609_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.genre'),
        ),
    ]
